github.com:
    git_protocol: ssh
    users:
        lxrdxe7o:
            oauth_token: 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
    user: lxrdxe7o
    oauth_token: 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
